
------Procedimientos almacenados----------

-- PROCEDIMIENTOS ALMACENADOS ESTUDIANTE --

CREATE PROC SP_BUSCAR_ESTUDIANTE
@BUSCAR VARCHAR(20)
AS
SELECT * FROM Tbl_Estudiantes
WHERE Nombre LIKE @BUSCAR + '%'
GO

CREATE PROC SP_AGREGAR_ESTUDIANTE 
@ID_MATRICULA INT,
@NOMBRE VARCHAR(30),
@APELLIDO VARCHAR(30),
@TELEFONO INT,
@DIRECCION VARCHAR(50),
@TIPO_IDENTIFICACION VARCHAR(20),
@NUM_IDENTIFICACION VARCHAR
AS
INSERT INTO TBL_ESTUDIANTES (ID_MATRICULA, NOMBRE, APELLIDO, TELEFONO, DIRECCION, TIPO_IDENTIFICACION, NUM_IDENTIFICACION)
						VALUES (@ID_MATRICULA, @NOMBRE, @APELLIDO, @TELEFONO, @DIRECCION, @TIPO_IDENTIFICACION, @NUM_IDENTIFICACION)
GO

CREATE PROC SP_EDITAR_ESTUDIANTE
@ID_MATRICULA INT,
@NOMBRE VARCHAR(30),
@APELLIDO VARCHAR(30),
@TELEFONO INT,
@DIRECCION VARCHAR(50),
@TIPO_IDENTIFICACION VARCHAR(20),
@NUM_IDENTIFICACION VARCHAR
AS
UPDATE TBL_ESTUDIANTES SET id_Matricula = @ID_MATRICULA,
							nombre = @NOMBRE,
							apellido = @APELLIDO,
							telefono = @TELEFONO,
							direccion = @DIRECCION,
							tipo_Identificacion = @TIPO_IDENTIFICACION,
							num_Identificacion = @NUM_IDENTIFICACION
							WHERE id_Matricula = @ID_MATRICULA
GO

CREATE PROC SP_BORRAR_ESTUDIANTE
@ID_MATRICULA int
as
delete from Tbl_Estudiantes
         where id_Matricula = @ID_MATRICULA
go


--PROCEDIMIENTOS ALMACENADOS LIBROS--

CREATE PROC SP_BUSCAR_LIBRO
@BUSCAR VARCHAR(20)
AS
SELECT * FROM Tbl_Libros
WHERE titulo LIKE @BUSCAR + '%'
GO

CREATE PROC SP_AGREGAR_LIBRO
@ID_SIGNATURA VARCHAR(7),
@TITULO VARCHAR(50),
@SUBTITULO VARCHAR(50),
@AUTOR VARCHAR(50),
@EDITORIAL VARCHAR(50),
@GENERO VARCHAR(20),
@AÑO_PUBLICACION INT
AS
INSERT INTO Tbl_Libros (id_Signatura, titulo, subtitulo, autor, editorial, genero, año_Publicacion)
						VALUES (@ID_SIGNATURA, @TITULO, @SUBTITULO, @AUTOR, @EDITORIAL, @GENERO, @AÑO_PUBLICACION)
GO

CREATE PROC SP_EDITAR_LIBRO
@ID_SIGNATURA VARCHAR(7),
@TITULO VARCHAR(50),
@SUBTITULO VARCHAR(50),
@AUTOR VARCHAR(50),
@EDITORIAL VARCHAR(50),
@GENERO VARCHAR(20),
@AÑO_PUBLICACION INT
AS
UPDATE Tbl_Libros SET id_Signatura = @ID_SIGNATURA,
					titulo = @TITULO,
					subtitulo = @SUBTITULO,
					autor = @SUBTITULO,
					editorial = @EDITORIAL,
					genero = @GENERO,
					año_Publicacion = @AÑO_PUBLICACION
GO

CREATE PROC SP_BORRAR_LIBRO
@ID_SIGNATURA INT
AS
DELETE FROM Tbl_Libros
		WHERE id_Signatura = @ID_SIGNATURA
GO


--PROCEDIMIENTOS ALMACENADOS PRESTAMOS--

CREATE PROC SP_BUSCAR_PRESTAMO
@ID_P INT,
@ID_MATRICULA INT,
@ID_SIGNATURA VARCHAR
AS
SELECT * FROM Tbl_Prestamos
		WHERE id_P = @ID_P AND
			  id_Matricula = @ID_MATRICULA OR
			  id_Signatura = @ID_SIGNATURA
GO

CREATE PROC SP_AGREGAR_PRESTAMO
@ID_ESTUDIANTE INT,
@ID_LIBRO VARCHAR,
@F_PRESTAMO DATETIME
AS
INSERT INTO Tbl_Prestamos (id_Matricula, id_Signatura, f_Prestamo)
						VALUES ( @ID_ESTUDIANTE, @ID_LIBRO, @F_PRESTAMO)
GO

CREATE PROC SP_EDITAR_PRESTAMO
@ID_P INT,
@ID_ESTUDIANTE INT,
@ID_LIBRO VARCHAR,
@F_PRESTAMO DATETIME
AS
UPDATE Tbl_Prestamos SET id_P = @ID_P
					WHERE id_Matricula = @ID_ESTUDIANTE AND
						  id_Signatura = @ID_LIBRO AND
						  f_Prestamo = @F_PRESTAMO
GO

CREATE PROC SP_BORRAR_PRESTAMO
@ID_P INT,
@ID_ESTUDIANTE INT
AS
DELETE FROM Tbl_Prestamos
		WHERE id_P = @ID_P AND
			  id_Matricula = @ID_ESTUDIANTE
GO

--Vistas--

CREATE PROC SP_LISTAR_ESTUDIANTE
AS
SELECT * FROM Tbl_Estudiantes
GO

CREATE PROC SP_LISTAR_LIBROS
AS
SELECT * FROM Tbl_Libros
GO

CREATE PROC SP_LISTAR_PRESTAMOS
AS
SELECT * FROM Tbl_Prestamos
GO
